project_id = "jouqghqhhccwstmjveen"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[fetch.functions]]
name = "get-turn-credentials"
verify_jwt = true