
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jouqghqhhccwstmjveen.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvdXFnaHFoaGNjd3N0bWp2ZWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzQ3NTgsImV4cCI6MjA1Mzg1MDc1OH0.YvH0FTszPZudNXZdCIBiCrXB5Ss1elWIZG3etGz87Rw";

// Create Supabase client with explicit headers configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'apikey': SUPABASE_ANON_KEY
    }
  }
});
